import { HeroDefinition, WeaponDefinition, ArenaDefinition } from '../types/game';

// Image assets generated for arenas and promo cover
export const COVER_IMAGE = '/src/assets/images/battle_cover_heroes_1790230892221.jpg';

export const HEROES: HeroDefinition[] = [
  {
    id: 'iron',
    name: 'IRON',
    title: 'The Iron Bastion',
    description: 'A hulking warrior encased in enchanted tempered steel. Slow to advance, but practically immovable and punishing up close.',
    style: 'Heavy Juggernaut',
    color: '#94a3b8',
    secondaryColor: '#334155',
    accentColor: '#f59e0b',
    stats: {
      hp: 1350,
      attack: 85,
      defense: 85,
      speed: 52,
      range: 65,
      energy: 100,
    },
    starterWeaponId: 'hammer',
    ability: {
      name: 'Iron Fortress',
      description: 'Slams the earth creating seismic shockwave pillars that pierce guard and blast opponents backward.',
      energyCost: 40,
      cooldown: 8000,
      type: 'slam',
    },
    unlockedByDefault: true,
    requiredLevel: 1,
  },
  {
    id: 'shadow',
    name: 'SHADOW',
    title: 'Whisper of Death',
    description: 'An ethereal assassin trained in forbidden smoke arts. Strikes with blistering speed and slips behind enemy lines.',
    style: 'Shadow Assassin',
    color: '#6366f1',
    secondaryColor: '#1e1b4b',
    accentColor: '#a855f7',
    stats: {
      hp: 920,
      attack: 96,
      defense: 45,
      speed: 95,
      range: 50,
      energy: 110,
    },
    starterWeaponId: 'daggers',
    ability: {
      name: 'Shadow Blink',
      description: 'Vanishes into a cloud of smoke and instantly executes a devastating surprise strike behind the target.',
      energyCost: 35,
      cooldown: 6500,
      type: 'teleport',
    },
    unlockedByDefault: true,
    requiredLevel: 1,
  },
  {
    id: 'valkyrie',
    name: 'VALKYRIE',
    title: 'Radiant Aegis',
    description: 'Champion of the celestial sky. Commands balanced martial prowess, piercing polearms, and solar light magic.',
    style: 'Divine Vanguard',
    color: '#fbbf24',
    secondaryColor: '#78350f',
    accentColor: '#fef08a',
    stats: {
      hp: 1120,
      attack: 82,
      defense: 72,
      speed: 76,
      range: 85,
      energy: 100,
    },
    starterWeaponId: 'spear',
    ability: {
      name: 'Spear of Light',
      description: 'Hurls a blinding bolt of solar lightning across the arena, causing heavy stagger and knockback.',
      energyCost: 40,
      cooldown: 7500,
      type: 'beam',
    },
    unlockedByDefault: true,
    requiredLevel: 1,
  },
  {
    id: 'blade',
    name: 'BLADE',
    title: 'Sword Saint',
    description: 'Master of lethal edge techniques. Chains rapid katana and longsword flourishes that easily punish opponent openings.',
    style: 'Sword Saint',
    color: '#ef4444',
    secondaryColor: '#450a0a',
    accentColor: '#fca5a5',
    stats: {
      hp: 1060,
      attack: 92,
      defense: 65,
      speed: 84,
      range: 75,
      energy: 105,
    },
    starterWeaponId: 'katana',
    ability: {
      name: 'Omnislash',
      description: 'Unleashes a rapid barrage of four consecutive dimensional cuts through the enemy in the blink of an eye.',
      energyCost: 50,
      cooldown: 8500,
      type: 'dash',
    },
    unlockedByDefault: true,
    requiredLevel: 1,
  },
  {
    id: 'raven',
    name: 'RAVEN',
    title: 'Deadeye Warden',
    description: 'A solitary marksman draped in raven plumage. Dominates combat from long distances with lethal bow precision.',
    style: 'Deadeye Marksman',
    color: '#06b6d4',
    secondaryColor: '#0e7490',
    accentColor: '#67e8f9',
    stats: {
      hp: 960,
      attack: 88,
      defense: 50,
      speed: 80,
      range: 98,
      energy: 120,
    },
    starterWeaponId: 'bow',
    ability: {
      name: 'Raven Tempest',
      description: 'Releases a swarm of razor-sharp spirit ravens that track and bombard the target from above.',
      energyCost: 45,
      cooldown: 9000,
      type: 'projectile',
    },
    unlockedByDefault: false,
    requiredLevel: 2,
  },
  {
    id: 'titan',
    name: 'TITAN',
    title: 'Colossus of Ruin',
    description: 'A primal giant awakened from molten deeps. Every blow shatters armor and sends opponents flying.',
    style: 'Colossal Berserker',
    color: '#ea580c',
    secondaryColor: '#7c2d12',
    accentColor: '#fdba74',
    stats: {
      hp: 1480,
      attack: 100,
      defense: 82,
      speed: 48,
      range: 70,
      energy: 90,
    },
    starterWeaponId: 'axe',
    ability: {
      name: 'Seismic Crater',
      description: 'Leaps high into the air and crashes down with a cataclysmic fiery eruption that rocks the entire arena.',
      energyCost: 50,
      cooldown: 9500,
      type: 'slam',
    },
    unlockedByDefault: false,
    requiredLevel: 3,
  },
  {
    id: 'phantom',
    name: 'PHANTOM',
    title: 'Spectral Duelist',
    description: 'A master of illusion wrapped in icy blue apparitions. Evades attacks with effortless phase-shifting.',
    style: 'Evasive Trickster',
    color: '#38bdf8',
    secondaryColor: '#0369a1',
    accentColor: '#bae6fd',
    stats: {
      hp: 1000,
      attack: 84,
      defense: 58,
      speed: 92,
      range: 68,
      energy: 130,
    },
    starterWeaponId: 'magic_blade',
    ability: {
      name: 'Spectral Decoy',
      description: 'Phases backward leaving behind an unstable energy decoy that detonates when touched by the opponent.',
      energyCost: 40,
      cooldown: 7000,
      type: 'clone',
    },
    unlockedByDefault: false,
    requiredLevel: 4,
  },
  {
    id: 'arcane',
    name: 'ARCANE',
    title: 'Archmage of the Void',
    description: 'Commands ancient cosmos and void spheres. Controls the arena with homing sorceries and reality-warping blasts.',
    style: 'Mystic Magus',
    color: '#d946ef',
    secondaryColor: '#701a75',
    accentColor: '#f0abfc',
    stats: {
      hp: 940,
      attack: 98,
      defense: 52,
      speed: 72,
      range: 92,
      energy: 150,
    },
    starterWeaponId: 'staff',
    ability: {
      name: 'Arcane Supernova',
      description: 'Summons an expanding core of cosmic energy that discharges multiple orbiting stellar projectiles.',
      energyCost: 55,
      cooldown: 10000,
      type: 'nova',
    },
    unlockedByDefault: false,
    requiredLevel: 5,
  },
];

export const WEAPONS: WeaponDefinition[] = [
  // --- MELEE ---
  {
    id: 'sword',
    name: 'Bastard Longsword',
    type: 'melee',
    description: 'Balanced steel double-edged blade. Reliable swing arcs and solid parry defense.',
    damage: 38,
    speed: 78,
    range: 75,
    radius: 52,
    cooldown: 280,
    critChance: 0.12,
    color: '#cbd5e1',
    icon: '⚔️',
    unlockedByDefault: true,
    requiredLevel: 1,
  },
  {
    id: 'katana',
    name: 'Muramasa Katana',
    type: 'melee',
    description: 'Forged from folded shadow steel. Extremely swift draw attacks with high critical strike rate.',
    damage: 35,
    speed: 92,
    range: 74,
    radius: 46,
    cooldown: 220,
    critChance: 0.25,
    color: '#f43f5e',
    icon: '🗡️',
    unlockedByDefault: true,
    requiredLevel: 1,
  },
  {
    id: 'axe',
    name: 'Obsidian Battleaxe',
    type: 'melee',
    description: 'Heavy cleaving greataxe capable of sundering enemy guards with sheer rotational force.',
    damage: 54,
    speed: 54,
    range: 68,
    radius: 64,
    cooldown: 410,
    critChance: 0.15,
    color: '#f97316',
    icon: '🪓',
    unlockedByDefault: true,
    requiredLevel: 1,
  },
  {
    id: 'spear',
    name: 'Celestial Lance',
    type: 'melee',
    description: 'Long silver spear that keeps opponents at distance with safe, high-velocity thrusts.',
    damage: 42,
    speed: 74,
    range: 108,
    radius: 38,
    cooldown: 330,
    critChance: 0.14,
    color: '#facc15',
    icon: '🔱',
    unlockedByDefault: true,
    requiredLevel: 1,
  },
  {
    id: 'hammer',
    name: 'Thunderforge Hammer',
    type: 'melee',
    description: 'Gigantic war hammer with massive stopping power. Inflicts heavy stun and ground impact shockwaves.',
    damage: 64,
    speed: 44,
    range: 65,
    radius: 68,
    cooldown: 480,
    critChance: 0.20,
    color: '#94a3b8',
    icon: '🔨',
    unlockedByDefault: true,
    requiredLevel: 1,
  },
  {
    id: 'daggers',
    name: 'Twin Nightfangs',
    type: 'melee',
    description: 'Dual serrated daggers allowing ultra-fast combo chains and quick recovery windows.',
    damage: 26,
    speed: 100,
    range: 48,
    radius: 36,
    cooldown: 170,
    critChance: 0.28,
    color: '#818cf8',
    icon: '🔪',
    unlockedByDefault: true,
    requiredLevel: 1,
  },

  // --- RANGED ---
  {
    id: 'bow',
    name: 'Shadow Hawk Bow',
    type: 'ranged',
    description: 'Lightweight composite bow that shoots high-velocity piercing arrows across the arena.',
    damage: 36,
    speed: 70,
    range: 360,
    radius: 30,
    cooldown: 440,
    critChance: 0.18,
    color: '#22d3ee',
    icon: '🏹',
    unlockedByDefault: true,
    requiredLevel: 2,
  },
  {
    id: 'crossbow',
    name: 'Arbalest Heavy Crossbow',
    type: 'ranged',
    description: 'Mechanized arbalest firing armor-piercing heavy bolts with intense knockback.',
    damage: 50,
    speed: 52,
    range: 400,
    radius: 35,
    cooldown: 520,
    critChance: 0.22,
    color: '#f59e0b',
    icon: '🎯',
    unlockedByDefault: false,
    requiredLevel: 3,
  },
  {
    id: 'throwing_knives',
    name: 'Venom Throwing Knives',
    type: 'ranged',
    description: 'Rapidly hurls paired steel blades that catch dodging foes off-guard.',
    damage: 24,
    speed: 88,
    range: 280,
    radius: 28,
    cooldown: 260,
    critChance: 0.20,
    color: '#10b981',
    icon: '⚡',
    unlockedByDefault: false,
    requiredLevel: 2,
  },

  // --- MAGIC ---
  {
    id: 'staff',
    name: 'Staff of the Eclipse',
    type: 'magic',
    description: 'Ancient conduit that releases homing stellar orbs and emits a pulsing protective aura.',
    damage: 44,
    speed: 66,
    range: 320,
    radius: 54,
    cooldown: 390,
    critChance: 0.16,
    color: '#c084fc',
    icon: '🪄',
    unlockedByDefault: false,
    requiredLevel: 4,
  },
  {
    id: 'magic_blade',
    name: 'Ether Brand',
    type: 'magic',
    description: 'A blade woven of condensed pure ether that sends crescent arc waves with every slash.',
    damage: 46,
    speed: 82,
    range: 92,
    radius: 56,
    cooldown: 290,
    critChance: 0.22,
    color: '#38bdf8',
    icon: '✨',
    unlockedByDefault: false,
    requiredLevel: 3,
  },
  {
    id: 'energy_orbs',
    name: 'Void Star Orbs',
    type: 'magic',
    description: 'Hovering mystical focus orbs firing tri-bursts of cosmic plasma into the opponent.',
    damage: 38,
    speed: 76,
    range: 290,
    radius: 46,
    cooldown: 320,
    critChance: 0.18,
    color: '#e879f9',
    icon: '🔮',
    unlockedByDefault: false,
    requiredLevel: 5,
  },
];

export const ARENAS: ArenaDefinition[] = [
  {
    id: 'castle',
    name: 'Medieval Castle',
    theme: 'Gothic Fortress',
    description: 'Ancient twilight stronghold with stone ramparts, torn battle flags, and flickering torches.',
    imagePath: '/src/assets/images/arena_medieval_castle_1790230841638.jpg',
    ambientParticles: 'torch_embers',
    floorColor: '#1e293b',
    ambientColor: '#f97316',
  },
  {
    id: 'forest',
    name: 'Dark Forest',
    theme: 'Enchanted Woods',
    description: 'Eerie moonlit glade surrounded by twisted elder oaks and ethereal glowing mist.',
    imagePath: '/src/assets/images/arena_dark_forest_1790230855803.jpg',
    ambientParticles: 'fireflies',
    floorColor: '#0f172a',
    ambientColor: '#38bdf8',
  },
  {
    id: 'city',
    name: 'Ruined City',
    theme: 'Crumbling Metropolis',
    description: 'War-torn gothic cityscape beneath an apocalyptic burning orange sky.',
    imagePath: '/src/assets/images/arena_ruined_city_1790230868440.jpg',
    ambientParticles: 'embers_smoke',
    floorColor: '#18181b',
    ambientColor: '#ea580c',
  },
  {
    id: 'arcane',
    name: 'Arcane Sanctum',
    theme: 'Cosmic Rift',
    description: 'Floating obsidian runic monoliths drifting along celestial vortex streams.',
    imagePath: '/src/assets/images/arena_arcane_sanctum_1790230880913.jpg',
    ambientParticles: 'arcane_motes',
    floorColor: '#090514',
    ambientColor: '#c084fc',
  },
  {
    id: 'desert',
    name: 'Desert Ruins',
    theme: 'Sunken Temple',
    description: 'Sunken sand-swept temple pillars buried deep within howling dune storms.',
    imagePath: undefined, // procedural stylized fallback rendering
    ambientParticles: 'sandstorm',
    floorColor: '#291e12',
    ambientColor: '#d97706',
  },
];
